AppBundle\Entity\AppUsers:
    type: entity
    table: app_users
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            fixed: false
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
        activationkey:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: activationKey
        isActive:
            type: boolean
            nullable: false
            column: is_active
    lifecycleCallbacks: {  }
