AppBundle\Entity\Collectionsquotes:
    type: entity
    table: collectionsquotes
    indexes:
        quote_id:
            columns:
                - quote_id
                - user_id
        user_id:
            columns:
                - user_id
        coll_id:
            columns:
                - coll_id
        IDX_5B8D23DBDB805178:
            columns:
                - quote_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createAt:
            type: datetime
            nullable: false
            column: create_at
    manyToOne:
        quote:
            targetEntity: Quotes
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                quote_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: AppUsers
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        coll:
            targetEntity: Collections
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                coll_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
