AppBundle\Entity\Nationalityhits:
    type: entity
    table: nationalityhits
    indexes:
        nationality_id:
            columns:
                - nationality_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nationalityId:
            type: integer
            nullable: false
            unsigned: false
            column: nationality_id
        ip:
            type: string
            nullable: false
            length: 50
            fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    lifecycleCallbacks: {  }
