AppBundle\Entity\Profession:
    type: entity
    table: profession
    uniqueConstraints:
        name:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
        slug:
            type: string
            nullable: false
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
