AppBundle\Entity\Quotes:
    type: entity
    repositoryClass: AppBundle\Entity\QuotesRepository
    table: quotes
    indexes:
        author_id:
            columns:
                - author_id
    uniqueConstraints:
        quote:
            columns:
                - quote
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        quote:
            type: string
            nullable: false
            length: 255
            fixed: false
        image:
            type: string
            nullable: false
            length: 255
            fixed: false
        keywords:
            type: string
            nullable: false
            length: 255
            fixed: false
    manyToOne:
        author:
            targetEntity: Authors
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                author_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
