AppBundle\Entity\Topicshits:
    type: entity
    table: topicshits
    indexes:
        quote_id:
            columns:
                - topic_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ip:
            type: string
            nullable: false
            length: 50
            fixed: false
        createAt:
            type: datetime
            nullable: false
            column: create_at
    manyToOne:
        topic:
            targetEntity: Topics
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                topic_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
