AppBundle\Entity\Userfavorites:
    type: entity
    table: userfavorites
    indexes:
        user_id:
            columns:
                - user_id
                - quote_id
        quote_id:
            columns:
                - quote_id
        IDX_2A24C195A76ED395:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    manyToOne:
        quote:
            targetEntity: Quotes
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                quote_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: AppUsers
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
